Quiet loop logs; improve loop intervals
PrefectHQ/server pull request #43
Opened 2020-08-14 14:42 UTC by jlowin

**Thanks for contributing to Prefect Server!**

Please describe your work and make sure your PR:

- [x] adds new tests (if appropriate)
- [x] adds a changelog entry to the `changes/` directory (if appropriate)

Note that your PR will not be reviewed unless these two boxes are checked.

## What does this PR change?
This PR:
- Quiets debug logs from loop services to heartbeat no more than once every 5 minutes. For rapid services, the noise from heartbeating every loop makes working with logs difficult
- Improves the loop interval calculation so it starts from the beginning of each period not the end. If a service takes one hour to run and has a loop interval of 24 hours, this means it will now start every 24 hours instead of every 25 hours.
- Adds a warning if the loop interval is shorter than the execution time (which would lead to too-rapid execution without pauses)

2020-08-17 22:03 UTC, cicdw commented on src/prefect_server/services/loop_service.py
> +            await asyncio.sleep((next_run - pendulum.now("UTC")).total_seconds())
Can you add a test for a loop service whose `run_once` consistently takes longer than `loop_seconds_default`?

2020-08-18 00:51 UTC, jlowin commented
@cicdw made the following changes:
- added a `stop()` method to facilitate testing and interactive use (otherwise the services run infinitely)
- added tests, including for the situation you described
- removed the random starting delay - overengineered ✅ 
- turned on asyncio debug mode

2020-12-30 05:04 UTC, cicdw commented
Closing this as we've made (most of) these adjustments elsewhere.

2021-01-28 22:29 UTC, jlowin commented
Reopening following offline conversation that the remaining enhancements in this PR may be desirable

2021-02-01 17:17 UTC, cicdw requested changes
Minor request to reuse an existing attribute, otherwise this LGTM

2021-02-01 17:17 UTC, cicdw commented on src/prefect_server/services/loop_service.py
> +        self._stop_running = False
we already have an `_is_running` attribute that you should probably reuse instead

2021-02-03 16:43 UTC, cicdw approved these changes
LGTM - this will be a nice QOL improvement

2021-02-03 16:43 UTC, merged